# Configuration file
# key = value jdbc:h2:mem:testdb
"%prod":
  quarkus:
    log:
      console:
        format: "%d{HH:mm:ss} %-5p traceId=%X{traceId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n"
    jaeger:
      service-name: Cliente
      sampler-type: const
      sampler-param: 1
    datasource:
      db-kind: mysql
      username: root
      password: abc@123
      jdbc:
        url: jdbc:mysql://35.222.194.73:3306/MarketCodeCliente
    hibernate-orm:
      dialect:
        ~: org.hibernate.dialect.MySQL57InnoDBDialect
      database:
        generation:
          ~: update

"%dev":
  quarkus:
    log:
      console:
        format: "%d{HH:mm:ss} %-5p traceId=%X{traceId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n"
    jaeger:
      service-name: Cliente
      sampler-type: const
      sampler-param: 1
    datasource:
      db-kind: mysql
      username: root
      password: abc@123
      jdbc:
        url: jdbc:mysql://localhost:3306/MarketCodeCompra
    hibernate-orm:
      dialect:
        ~: org.hibernate.dialect.MySQL57InnoDBDialect
      database:
        generation:
          ~: update

"%test":
  quarkus:
    datasource:
      db-kind: h2
      username: root
      password: abc@123
      jdbc:
        url: jdbc:h2:~/test
    hibernate-orm:
      dialect:
        ~: org.hibernate.dialect.H2Dialect
      database:
        generation:
          ~: drop-and-create

quarkus:
  swagger-ui:
    always-include: true
    path: /documentacao
