# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Action build native

on: [push]

jobs:
  native_build:
    runs-on: quay.io/repository/quarkus/centos-quarkus-maven?tag=19.3.2-java11
    name: Build native Quarkus app
    steps:
      - name: Checkout the code
        uses: actions/checkout@master
      - name: Build native executable
        uses: maxday/quarkus-native-build-docker-action@1
        with:
          outputName: app-runner
      - name: Upload native executable
        uses: actions/upload-artifact@v1
        with:
          name: native-executable
          path: app-runner
